[project]
name = "homeassistant-unas-pro"
version = "0.3.5"
description = "Monitoring and fan control for UniFi UNAS Pro with native Home Assistant integration."
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=25.1.0",
    "asyncssh>=2.22.0",
    "homeassistant>=2025.12.5",
]
